export const recipes = [
  {
    id: '1',
    image:
      'https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg',
    name: 'Spaghetti Bolognese',
    cuisine: 'Indian',
    ingredients: [
      'spaghetti',
      'ground beef',
      'onion',
      'garlic',
      'canned tomatoes',
      'tomato paste',
      'dried oregano',
      'salt',
      'black pepper',
      'Parmesan cheese (for garnish)',
    ],
    instructions: [
      'Cook the spaghetti according to package instructions.',
      'In a large pan, brown the ground beef over medium heat.',
      'Add the chopped onion and minced garlic to the pan. Sauté until the onion is translucent.',
      'Add the canned tomatoes, tomato paste, dried oregano, salt, and black pepper to the pan. Stir well to combine.',
      'Simmer the sauce for 15-20 minutes, stirring occasionally.',
      'Serve the spaghetti topped with the Bolognese sauce and garnish with grated Parmesan cheese.',
    ],
  },
  {
    id: '2',
    image:
      'https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg',
    name: 'Chicken Tikka Masala',
    cuisine: 'Indian',
    ingredients: [
      'boneless chicken',
      'plain yogurt',
      'tikka masala spice blend',
      'vegetable oil',
      'onion',
      'garlic',
      'ginger',
      'crushed tomatoes',
      'heavy cream',
      'salt',
    ],
    instructions: [
      'In a bowl, mix the chicken cubes with yogurt and tikka masala spice blend. Marinate for at least 1 hour.',
      'Heat the vegetable oil in a pan over medium heat. Add the chopped onion and sauté until golden brown.',
      'Add the minced garlic and grated ginger to the pan. Cook for another minute.',
      'Add the marinated chicken to the pan and cook until browned on all sides.',
      'Pour in the crushed tomatoes and simmer for 15 minutes, stirring occasionally.',
      'Stir in the heavy cream and cook for an additional 5 minutes.',
      'Season with salt to taste and serve the Chicken Tikka Masala with steamed rice or naan bread.',
    ],
  },
  {
    id: '3',
    image:
      'https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg',
    name: 'Caesar Salad',
    cuisine: 'American',
    ingredients: [
      'romaine lettuce',
      'croutons',
      'Parmesan cheese',
      'olive oil',
      'lemon juice',
      'Dijon mustard',
      'garlic',
      'salt',
      'pepper',
    ],
    instructions: [
      'Wash and dry the romaine lettuce. Tear it into bite-sized pieces and place in a large salad bowl.',
      'Add the croutons and grated Parmesan cheese to the bowl.',
      'In a small bowl, whisk together the olive oil, lemon juice, Dijon mustard, minced garlic, salt, and pepper.',
      'Pour the dressing over the salad and toss well to coat.',
      'Serve the Caesar Salad immediately as a side dish or add grilled chicken or shrimp for a complete meal.',
    ],
  },
  {
    id: '4',
    image:
      'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg',
    name: 'Sushi Rolls',
    cuisine: 'Japanese',
    ingredients: [
      'sushi rice',
      'nori seaweed sheets',
      'fish (e.g., salmon, tuna)',
      'vegetables (e.g., cucumber, avocado)',
      'soy sauce',
      'wasabi',
      'pickled ginger',
    ],
    instructions: [
      'Prepare the sushi rice according to package instructions.',
      'Place a sheet of nori on a bamboo sushi mat.',
      'Spread a thin layer of sushi rice on top of the nori, leaving a small border at the top.',
      'Add strips of fish and vegetables in the center of the rice.',
      'Roll the sushi tightly using the bamboo mat, applying gentle pressure.',
      'Slice the sushi roll into bite-sized pieces.',
      'Serve the sushi rolls with soy sauce, wasabi, and pickled ginger.',
    ],
  },
  {
    id: '5',
    image:
      'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg',
    name: 'Guacamole',
    cuisine: 'Mexican',
    ingredients: [
      'avocado',
      'lime juice',
      'red onion',
      'tomato',
      'cilantro',
      'jalapeno',
      'garlic',
      'salt',
      'pepper',
    ],
    instructions: [
      'Cut the avocado in half, remove the pit, and scoop the flesh into a bowl.',
      'Add lime juice to the bowl and mash the avocado with a fork or a potato masher.',
      'Finely chop the red onion, tomato, cilantro, jalapeno, and garlic. Add them to the bowl.',
      'Season with salt and pepper, and mix well to combine all the ingredients.',
      'Taste and adjust the seasoning if needed.',
      'Serve the guacamole with tortilla chips or as a topping for tacos, burritos, or quesadillas.',
    ],
  },
  // Add more recipe objects as needed
];
